schedule: "0 * * * *"
github: {}
backups:
  - user: notheotherben
    filters:
      - !Include ["nix-env"]
  - org: SierraSoftworks
    filters:
      - !Include ["git-tool", "grey"]
      - !Public
      - !NonFork