schedule: "0 * * * *"

backups:
  - kind: github/repo
    from: users/notheotherben
    filters:
      - !Include ["notheotherben/nix-env"]
  - kind: github/repo
    from: orgs/SierraSoftworks
    filters:
      - !Include ["SierraSoftworks/git-tool", "SierraSoftworks/grey"]
      - !Is public
      - !IsNot fork
  - kind: github/release
    from: orgs/SierraSoftworks
    filters:
      - !Include ["SierraSoftworks/grey"]
      - !Is public
      - !IsNot fork
