schedule: "0 * * * *"

backups:
  - kind: github/repo
    from: users/notheotherben
    filters:
      - !Include ["nix-env"]
  - kind: github/repo
    from: orgs/SierraSoftworks
    filters:
      - !Include ["git-tool", "grey"]
      - !Is public
      - !IsNot fork
