schedule: "0 * * * *"

backups:
  - kind: github/repo
    from: users/notheotherben
    filter: repo.name == "nix-env"
  - kind: github/repo
    from: orgs/SierraSoftworks
    filter: repo.public && !repo.fork && repo.name in ["git-tool", "grey"]
  - kind: github/release
    from: orgs/SierraSoftworks
    filter: repo.public && !release.prerelease && !artifact.source-code
